stages:
  - deploy
deploy:
  stage: deploy
  only:
    - master
  tags:
    - srv23154
  script:
    - rsync -r ./ /home/razrab/errands_system/
    - cd /home/razrab/docker/ && docker-compose build && docker-compose up -d
    - docker exec errands_system python manage.py migrate
    - cd /home/razrab/docker/ && docker-compose build && docker-compose up -d