stages:
  - deploy
deploy:
  stage: deploy
  only:
    - master
  tags:
    - srv2363
  script:
    - rsync -r ./ /home/uizo/shady/errands_system

job:
  stage: deploy
  script:
    - sudo supervisorctl restart errands_system